'''
    Compile messages for each user in input file
    
    Output to standard out in format:
    <sender> <text1> <text2> ...
    
    usage: python A_messages.py <sorted_message_text_file>
    
    Input file should be in format:
    <sender> <recipient> <text>
    
    Message text file must be sorted
    Sorting can be done with the unix sort command as follows:
    sort -k1n,1 -k2n,2 <message_text_file> > <sorted_message_text_file>
    
    Original message text file can be generated by using extract_from_json.py
    with a fields file with the line:
    user:id in_reply_to_status_id text
    and input being the json files that contain the statuses
    
    '''


import sys

def user(line):
	return line[:line.find(' ')]


def message_text(line):
    text = line[line.find(' ')+1:]
    return text[text.find(' ')+1:].strip()


def main(argv):
	filename = argv[0]
	current = ''
	to_print = 'first'
	for line in open(filename):
		if not line.strip(): continue
		if user(line) == current:
			print to_print,
			print '  '+message_text(line),
			to_print = ''
		else: to_print = '\n'+user(line)+'  '+message_text(line)
		current = user(line)

if __name__ == '__main__':
    main(sys.argv[1:])